### ISSUE TITLE
how to set a proper -train_steps during training a coqa-base model

### ISSUE THREAD

**Issue by kiss2smiles** [stanfordnlp/coqa-baselines#1]
background: because of the changing of the parameters in the latest OpenNMT-py version , the parameter "-epochs " has changed to "-train_steps".

question: If I need to train Conversational models and The pipeline model, how to set a proper -train_steps instead of -epochs.Do I need to git clone the older OpenNMT-py version?

**Comment by danqi** [comment]
I am aware of that issue and I suggest you to use the exact same version as we did to reproduce the experiments. Just run  `git clone --recurse-submodules git@github.com:stanfordnlp/coqa-baselines.git`.
