### ISSUE TITLE
Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts

### ISSUE THREAD

**Issue by susht3** [stanfordnlp/coqa-baselines#2]
git clone --recurse-submodules git@github.com:stanfordnlp/coqa-baselines.git

Cloning into 'coqa-baselines'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Erutan-pku** [comment]
I also meet this problem. How did you solve it? 
Thank you~~
