### ISSUE TITLE
Does this repo contain the code for abstractive answer? Thank you very much!

### ISSUE THREAD

**Issue by guotong1988** [stanfordnlp/coqa-baselines#9]
![image](https://user-images.githubusercontent.com/4702353/51152278-deea1a80-18a7-11e9-9319-bff03ca2c8ee.png)

@danqi @sivareddyg Thank you!

And do you know where is the better code for abstractive answer?

**Comment by sivareddyg** [comment]
Yes. You should use ```git clone --recurse-submodules git@github.com:stanfordnlp/coqa-baselines.git``` to download everything including abstractive generation code (i.e., seq2seq). After that, you can see the code in coqa-baselines/seq2seq

**Comment by guotong1988** [comment]
Thank you very much!
And do you know where is the better code for abstractive answer and CoQA?
I have not find the abstractive generation code in https://github.com/momohuang/FlowQA
